DROP TABLE IF EXISTS agency;
DROP TABLE IF EXISTS news;
CREATE TABLE agency (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agency TEXT UNIQUE NOT NULL,
    url TEXT NOT NULL
);
CREATE TABLE news (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    headline TEXT NOT NULL,
    url TEXT NOT NULL,
    agency_id INTEGER NOT NULL,
    FOREIGN KEY
(agency_id) REFERENCES agency
(id),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
);