DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS agency;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;
CREATE TABLE agency (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agency TEXT UNIQUE NOT NULL,
    url TEXT NOT NULL
);
CREATE TABLE news (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    headline TEXT NOT NULL,
    url TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agency_id INTEGER NOT NULL,
    FOREIGN KEY
(agency_id) REFERENCES agency
(id)
);
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY
(author_id) REFERENCES user
(id)
);